server:
  port: 8080
  servlet:
    context-path: /remind-push
  # 设置关闭方式为优雅关闭
  shutdown: graceful
spring:
  # 优雅停机最大等待时间
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: zuji-remind-push-biz
logging:
  level:
    root: info
  file:
    path: ./logs

